### ISSUE TITLE
Random seeds to subsample

### ISSUE THREAD

**Issue by FelipeMSD** [knights-lab/analysis_SHOGUN#18]
Dear Benjamin,

Could you tell me if on the subsampling script you use the same or different random seeds for each depth?

Kind regards,
Felipe

**Comment by bhillmann** [comment]
I can try, but this was done several years ago. I used different random seeds for each depth, I believe, since that is the default. https://github.com/knights-lab/analysis_SHOGUN/blob/527b1c511605608e039555fb8d238a9ba98f36c4/scripts/subsample_fasta.py#L13

Unfortunately, I don't think I saved what seeds I used, but the ability to specify them is there.

**Comment by FelipeMSD** [comment]
Super! Thank you very much for the response!

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
